// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt_9m_eU1rSbnkq64Jeirzh36JCnI7znk',
    appId: '1:365105935039:web:3cc7cdabbd0fcba6640c0a',
    messagingSenderId: '365105935039',
    projectId: 'todo-75dcc',
    authDomain: 'todo-75dcc.firebaseapp.com',
    storageBucket: 'todo-75dcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEMJFZO09K72RrkTI05B-ZiQnlQ7d_16Q',
    appId: '1:365105935039:android:8cf748372ebb0a1e640c0a',
    messagingSenderId: '365105935039',
    projectId: 'todo-75dcc',
    storageBucket: 'todo-75dcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDYvH2Du79utD7AH8HqE8x5klE0VKKe9k',
    appId: '1:365105935039:ios:b8463e02e51ba542640c0a',
    messagingSenderId: '365105935039',
    projectId: 'todo-75dcc',
    storageBucket: 'todo-75dcc.appspot.com',
    iosClientId: '365105935039-lhveop6tluaji8sjg9o10hm5tunt4gaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDYvH2Du79utD7AH8HqE8x5klE0VKKe9k',
    appId: '1:365105935039:ios:4d8557d9965b765f640c0a',
    messagingSenderId: '365105935039',
    projectId: 'todo-75dcc',
    storageBucket: 'todo-75dcc.appspot.com',
    iosClientId: '365105935039-o3qh0alhpn2jujjkfsi51t32fvd06fbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
